name: Merge upstream branches
on:
  schedule:
    - cron:  '0,30 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Alyx'
          git config --global user.email 'thecakechicken@users.noreply.github.com'

          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/modmail-dev/Modmail.git
          git fetch upstream

          git checkout master
          git merge --no-edit upstream/master
          git push origin master
